name: sitespeed

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node_version: 10

      - name: sitespeed check
        run: |
          npm install -g sitespeed.io
          sitespeed.io -u https://kumaaaaa.com/ -d 2 -n 1 --budget.configPath ${{ GITHUB_WORKSPACE }}/.github/budge.json
