name: sitespeed

on:
  push:
    branchs:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node_version: 10

      - name: sitespeed check
        run: |
          cp .target_url /github/workspace/url
          npm install -g sitespeed.io
          sitespeed.io.cmd -u https://kumaaaaa.com/ -d 2 -n 1 --budget /github/workspace/.github/budget.json
